### ISSUE TITLE
provider framework is raising an error, even though behaving correctly

### ISSUE THREAD

**Issue by jabalsad** [wheatstalk/cdk-intrinsic-validator#102]
Hi,

Reading through the provider framework logs in SFN, I see this error for the `framework-isComplete-task`.

It appears that the validator is working correctly, but for some reason raises an error on each execution.

```
{
    "errorType": "Error",
    "errorMessage": "{\"RequestType\":\"Create\",\"ServiceToken\":\"[redacted]-IntrinsicValidatorProvider-3NtIPiD7h5Up\",\"ResponseURL\":\"https://cloudformation-custom-resource-response-useast1.s3.amazonaws.com/[redacted]/d6ca14e0-d2ee-11ec-b217-0a5ceb1028fb%7CIntrinsicValidatorResource68378903ABDF55B%7C992c913c-4934-4685-85de-42b6b2b6cd1a?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Date=20220621T234945Z&X-Amz-SignedHeaders=host&X-Amz-Expires=7200&X-Amz-Credential=[redacted]2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Signature=02b3f1140a326327aaa816d95a2c4400bc14df9e0b6ba756773982c24c211963\",\"StackId\":\"[redacted]",\"RequestId\":\"992c913c-4934-4685-85de-42b6b2b6cd1a\",\"LogicalResourceId\":\"IntrinsicValidatorResource68378903ABDF55B\",\"ResourceType\":\"AWS::CloudFormation::CustomResource\",\"ResourceProperties\":{\"ServiceToken\":\"arn:aws:lambda:us-east-1:[redacted]-IntrinsicValidatorProvider-3NtIPiD7h5Up\"},\"StateMachineExecutionArn\":\"arn:aws:states:us-east-1:[redacted]:execution:IntrinsicValidatorStateMachine503A46CB-yOJKYnVRlocM:12bae6af-86da-4f1c-99d7-9564053b4a0e\",\"PhysicalResourceId\":\"992c913c-4934-4685-85de-42b6b2b6cd1a\"}",
    "stack": [
        "Error: {\"RequestType\":\"Create\",\"ServiceToken\":\"arn:aws:lambda:us-east-1:[redacted]-IntrinsicValidatorProvider-3NtIPiD7h5Up\",\"ResponseURL\":\"https://cloudformation-custom-resource-response-useast1.s3.amazonaws.com/[redacted]/d6ca14e0-d2ee-11ec-b217-0a5ceb1028fb%7CIntrinsicValidatorResource68378903ABDF55B%7C992c913c-4934-4685-85de-42b6b2b6cd1a?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Date=20220621T234945Z&X-Amz-SignedHeaders=host&X-Amz-Expires=7200&X-Amz-Credential=[redacted]%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Signature=02b3f1140a326327aaa816d95a2c4400bc14df9e0b6ba756773982c24c211963\",\"StackId\":\"arn:aws:cloudformation:us-east-1:[redacted]/d6ca14e0-d2ee-11ec-b217-0a5ceb1028fb\",\"RequestId\":\"992c913c-4934-4685-85de-42b6b2b6cd1a\",\"LogicalResourceId\":\"IntrinsicValidatorResource68378903ABDF55B\",\"ResourceType\":\"AWS::CloudFormation::CustomResource\",\"ResourceProperties\":{\"ServiceToken\":\"arn:aws:lambda:us-east-1:[redacted]-IntrinsicValidatorProvider-3NtIPiD7h5Up\"},\"StateMachineExecutionArn\":\"arn:aws:states:us-east-1:[redacted]:execution:IntrinsicValidatorStateMachine503A46CB-yOJKYnVRlocM:12bae6af-86da-4f1c-99d7-9564053b4a0e\",\"PhysicalResourceId\":\"992c913c-4934-4685-85de-42b6b2b6cd1a\"}",
        "    at isComplete (/var/task/framework.js:1:1279)",
        "    at processTicksAndRejections (internal/process/task_queues.js:95:5)",
        "    at async Runtime.handler (/var/task/cfn-response.js:1:1474)"
    ]
}
```

**Comment by misterjoshua** [comment]
Interesting. Could you give me an example of code that causes the provider to error like that so I can try to reproduce it?

**Comment by jabalsad** [comment]
It's a textbook example:

```
    const alarm = new Alarm(this, "Errors", {
      comparisonOperator: ComparisonOperator.GREATER_THAN_THRESHOLD,
      threshold: 0,
      evaluationPeriods: 1,
      metric: // [redacted]
      treatMissingData: TreatMissingData.MISSING,
    });

    const rollbackAlarm = new CompositeAlarm(this, "RollbackAlarm", {
      alarmRule: AlarmRule.anyOf(alarm),
    })

    new IntrinsicValidator(this, 'IntrinsicValidator', {
      validations: [
        Validation.monitorAlarm({
          alarm: rollbackAlarm,
          duration: cdk.Duration.minutes(2),
        }),
      ],
    });

```

**Comment by jabalsad** [comment]
I'm going to check to see if this is still happening with the latest version of the CDK.

**Comment by misterjoshua** [comment]
> I've been unable to get to the root of the issue, but I'm pretty confident it has to do with the CustomResource provider code. So this is probably an issue with CDK more than anything else. I don't think it changes the behavior of cdk-intrinsic-validator which is what matters in this case.

Ok, great. Thanks for reporting this anyway - it's good to know.
